name: Build Latest

on: [ push, workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish PsbCGEnumerator -c Debug -o Build/ --no-restore
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: PsbCGEnumerator-${{ github.sha }}
        path: Build/
